import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const generated = join(here, "..", "src", "generated", "wire.ts");

test("the generated wire types say they are generated", () => {
    const content = readFileSync(generated, "utf8");
    // A generated file that does not say so is one somebody edits.
    assert.match(content, /Generated by `cd shared && cargo run --bin gen-types`/);
    assert.match(content, /Do not edit/);
});

test("the committed wire types match the Rust definitions", (t) => {
    // The failure this guards: someone edits shared/src, forgets to regenerate,
    // and the committed TypeScript silently describes the previous shape — the
    // exact drift the shared crate exists to prevent, reintroduced by process.
    let before: string;
    try {
        before = readFileSync(generated, "utf8");
        execFileSync("cargo", ["run", "--quiet", "--bin", "gen-types"], {
            cwd: join(here, "..", "..", "shared"),
            stdio: "pipe",
        });
    } catch (err) {
        // No cargo on this machine is a reason to skip, not to fail: the Node
        // side must stay testable without a Rust toolchain.
        t.skip(`could not run the generator: ${err instanceof Error ? err.message : err}`);
        return;
    }
    const after = readFileSync(generated, "utf8");
    assert.equal(
        after,
        before,
        "be/src/generated/wire.ts is stale — run `npm run types:build` and commit the result",
    );
});
